name: setup-java

on: [push, pull_request]

jobs:
  java_v1:
    name: Build with setup-java@v1 (${{ matrix.java }} ${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        arch: [ x86, x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.arch }}

      - name: Java version
        run: java -version

  java_v2:
    name: Build with setup-java@v2 (${{ matrix.java }} ${{ matrix.arch }} ${{ matrix.dist }} ${{ matrix.latest }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        arch: [ x86, x64 ]
        dist: [ adopt, zulu ]
        latest: [ true, false ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.arch }}
          distribution: ${{ matrix.dist }}
          check-latest: ${{ matrix.latest }}

      - name: Java version
        run: java -version
